"""
Rosalind
Problem Name: Complementing a Strand of DNA
"""


def reverse_complement(dna):
    dna = dna.replace('\n', '')

    complements = {
        'A': 'T',
        'C': 'G',
        'T': 'A',
        'G': 'C',
    }

    complemented = [complements[nt] for nt in dna]
    return ''.join(nt for nt in reversed(complemented))

dna = '''
GGCCGGAAGCATTCTGCTGAGGTCATAGGGATCGTTACGCCGGAAAAATT
CGCTCCAATGCTATATCAAACTCTTTTTGCCGGCACGATAAACTGTTCAC
GCCTAGTAGACCCGGCGATTTTTATCCGCTGGGATATGGAGCCCGCTACC
TCCTGATTAGTTACATAGATAAACGTCTGATTACATTACTGAACGCAAGA
AATCTGATAGGCCCCCCATGCCCCTGGGGTGCGTAACGCGAAGATGCTCA
CGCCGTTTAAGGGACCCATACTATAGTCGGTTACGGTACATAATTCCCTG
GTAGCTCCGTTGACACCGTTAACCGGCTTAGTACCCTCGATACACTCTAA
CAAGCGAGGGCGCTTCACTCTCCAAGCCTAACCGCAATCTAGATCAATTC
AGAGCACGAAGGTCGGCGCCTAGTTATGCTTACCACTGAAGACCGGCGGC
TCCGTCGTTCTTTCATTTAGCAATGTGGCAGCGGACCAAAAATGCCGGCG
CGCGCCAAGAACACCCCGGGAGTCCGCCCTACAGTCTGGAAGGTCATGTG
AGGGCAAGCTCATTATTAGCATTTTGGATTATGGTTTTCCAAACAGTCCT
CAGAAGGCGCTAGCGCTTGACCTTTAGGGTTAGTTCGCAACGACCAATCC
GGCGTCTCCCTTGTCACATTCTAATCAATTAGCGTCCGGCAATGACGCAT
TCGTCGCGGTATTGGACGATTCTGGACTAACAAGCACACATAATATCGAG
CGTCGCACGTACGTCTTTTTGTTGCTGCTTCGCTGCGTGTGTCCCACCCC
ATGAATCTATATGTAGGACGCATAATAACCCTCTCCCAATTGGCCACTCG
TCGCGGCTCTTGCGATCATGCTGACATCTCCTCCGAGCGGATTTGTCAAC
CATTATGGGTGGGCCTTCCGGATCTCCGTTTTACGCCAGGGATTTCCCAT
ATTTTGCAA
'''
print(reverse_complement(dna))
